language: ruby
sudo: false
rvm:
- 2.3.3

install: 
  - gem install jekyll
  - gem install bundler
  - bundle install 
  
script: 
  - bundle exec jekyll build || bundle exec jekyll serve

exclude: [vendor]
